# Generated by Django 2.1.4 on 2018-12-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20181219_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event1', models.CharField(default='0', max_length=20)),
                ('event2', models.CharField(default='0', max_length=20)),
                ('event3', models.CharField(default='0', max_length=20)),
                ('event4', models.CharField(default='0', max_length=20)),
                ('event5', models.CharField(default='0', max_length=20)),
                ('event6', models.CharField(default='0', max_length=20)),
                ('event7', models.CharField(default='0', max_length=20)),
                ('event8', models.CharField(default='0', max_length=20)),
                ('event9', models.CharField(default='0', max_length=20)),
                ('event10', models.CharField(default='0', max_length=20)),
                ('event11', models.CharField(default='0', max_length=20)),
                ('event12', models.CharField(default='0', max_length=20)),
                ('event13', models.CharField(default='0', max_length=20)),
                ('event14', models.CharField(default='0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
