# Generated by Django 2.1.4 on 2018-12-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='current_event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='users',
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
