# Generated by Django 2.1.4 on 2018-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20181219_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='token',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
