# Generated by Django 2.1.4 on 2018-12-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181220_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.CharField(default='', max_length=20),
        ),
    ]
