# Generated by Django 2.1.4 on 2018-12-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_registration_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
