# Generated by Django 2.1.4 on 2018-12-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='0', max_length=20)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Event')),
            ],
        ),
    ]
