# Generated by Django 2.1.4 on 2018-12-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ManyToManyField(to='myapp.Event'),
        ),
    ]
