# Generated by Django 2.1.4 on 2018-12-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20181220_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
    ]
