# Generated by Django 2.1.4 on 2018-12-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
