# Generated by Django 2.1.4 on 2018-12-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_eventrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrules',
            name='rules',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
